### ISSUE TITLE
Bug: Loading a save does not update "White's turn" UI

### ISSUE THREAD

**Issue by terite** [spherous/HexChess#14]
Reproduction steps:
1. Enter sandbox, make one move. It should now be black's turn
2. Save the game
3. Surrender and Reset. It should now be white to move.
4. Load the game from step 2
5. Observe that the UI says "White's Turn" but it's actually black's turn and only black pieces can be moved.

**Comment by spherous** [comment]
Fixed.
Removing the invoke of newTurn from set board state created this bug, I've added an invoke in the load game code, as well as a call to set the camera correctly.
