### ISSUE TITLE
Bug: Pawns captured by en passant don't get put back when loading games

### ISSUE THREAD

**Issue by terite** [spherous/HexChess#16]
Reproduction: 
1. Capture pawn via en passant
2. Load a different save game
3. Observe that the captured pawn is not in jail, but also not on the board

<details>
<summary>See recording</summary>
<img src="https://user-images.githubusercontent.com/44259/119693428-1f0b2180-be01-11eb-8861-a00f7a744a7e.gif"></details>

**Comment by terite** [comment]
A fix for this is in https://github.com/spherous/HexChess/pull/13/commits/0ed4c2adc4e214be8b806d5b0e2ee38f866c49f9

**Comment by spherous** [comment]
Merged in :) Ty ty
