### ISSUE TITLE
"com.unity.ml-agents.extensions" dependency is specified using a machine-specific path

### ISSUE THREAD

**Issue by terite** [spherous/HexChess#24]
![Untitled](https://user-images.githubusercontent.com/44259/141007283-a854af52-7afa-4eaf-ac0b-5a88004e20d3.png)

When running the project locally, I get unity errors related to not being able to load the dependency mentioned in the title. After removing the dependency from `manifest.json` I am able to run the project.

See: https://github.com/spherous/HexChess/blob/cab849bd0c2f81becf34e37203c8b7186c2d6248/Packages/manifest.json#L10

**Comment by spherous** [comment]
fixed in commit: 2948c0c1c123df614adab38b3eeda9a595fa33c3
Added external dependency to repo. ML-Agents is needed for existing ML AI to work. Closing issue.
